#!/bin/zsh
bindkey -v # vi keys

autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Docs for these widgets are kind of here:
# http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html
# Some details are here:
# https://github.com/zsh-users/zsh/tree/master/Functions/Zle

# These come from emacs mode. Anything that doesn't conflict gets to stay.
# Note: remember that ^[x means Alt+x, usually.

#MARKTODO# bindkey "^@" set-mark-command
bindkey "^A" beginning-of-line
bindkey "^B" backward-char
bindkey "^D" delete-char-or-list # if at end, show (but don't expand) expansions
bindkey "^E" end-of-line
bindkey "^F" forward-char
bindkey "^G" send-break
bindkey "^H" backward-delete-char
#already-there# bindkey "^I" expand-or-complete
#already-there# bindkey "^J" accept-line
bindkey "^K" kill-line
#already-there# bindkey "^L" clear-screen
#already-there# bindkey "^M" accept-line
bindkey "^N" down-line-or-history
bindkey "^O" accept-line-and-down-history # I wonder what this is for.
bindkey "^P" up-line-or-history
# "Push the current buffer onto the buffer stack and clear the buffer. Next
# time the editor starts up, the buffer will be popped off the top of the
# buffer stack and loaded into the editing buffer."
bindkey "^Q" push-line # TODO: figure this out
bindkey "^R" history-incremental-search-backward
bindkey "^S" history-incremental-search-forward
bindkey "^T" transpose-chars
#x#bindkey "^U" kill-whole-line # vi-kill-line is gentler. Which == better?
#already-there#bindkey "^V" quoted-insert # (as vi-quoted-insert)
#already-there#bindkey "^W" backward-kill-word # (as vi-backward-kill-word)
bindkey "^X^B" vi-match-bracket # vi: Esc %
bindkey "^X^F" vi-find-next-char # vi: Esc f
bindkey "^X^J" vi-join # vi: J
bindkey "^X^K" kill-buffer # similar to ^u^k
# Haven't fully figured this one out. Docs say, "Search in the history list
# for a line matching the current one and fetch the event following it.":
bindkey "^X^N" infer-next-history # TODO: figure this out
bindkey "^X^O" overwrite-mode # vi: Esc R
bindkey "^X^U" undo
bindkey "^X^V" vi-cmd-mode # Kinda like vim's ^O — one-shot vi cmd
#MARKTODO# bindkey "^X^X" exchange-point-and-mark
bindkey "^X*" expand-word # Why not just tab?
bindkey "^X=" what-cursor-position # Show char info, like vim ga + g^g
bindkey "^XG" list-expand # Show, but don't expand, expansion.
bindkey "^Xg" list-expand
bindkey "^Xr" history-incremental-search-backward # Same as ^r
bindkey "^Xs" history-incremental-search-forward # Same as ^s # For stty ixon?
bindkey "^Xu" undo
#MARKTODO# bindkey "^Y" yank
bindkey "^[^D" list-choices
bindkey "^[^G" send-break
#?# bindkey "^[^H" backward-kill-word
bindkey "^[^L" clear-screen
bindkey "^[^_" copy-prev-word
#?# bindkey "^[ " expand-history # Why not just tab? Seems like a waste.
bindkey "^[!" expand-history # Again, why not just tab? But OK.
#MARKTODO# bindkey "^[\"" quote-region
#?# bindkey "^[\$" spell-word
bindkey "^['" quote-line # Very useful. E.g. to echo a command into a file.
bindkey "^[-" neg-argument
bindkey "^[." insert-last-word # Alt+'.' gives !$'s value.
#don't like 'em# bindkey "^[0" digit-argument
#don't like 'em# bindkey "^[1" digit-argument
#don't like 'em# bindkey "^[2" digit-argument
#don't like 'em# bindkey "^[3" digit-argument
#don't like 'em# bindkey "^[4" digit-argument
#don't like 'em# bindkey "^[5" digit-argument
#don't like 'em# bindkey "^[6" digit-argument
#don't like 'em# bindkey "^[7" digit-argument
#don't like 'em# bindkey "^[8" digit-argument
#don't like 'em# bindkey "^[9" digit-argument
#…?# bindkey "^[<" beginning-of-buffer-or-history
#…?# bindkey "^[>" end-of-buffer-or-history
#x# bindkey "^[?" which-command
#x# bindkey "^[A" accept-and-hold
#x# bindkey "^[B" backward-word
#xx# #x# bindkey "^[C" capitalize-word
#x# bindkey "^[D" kill-word
#x# bindkey "^[F" forward-word
#x# bindkey "^[G" get-line
#x# bindkey "^[H" run-help
#xx# #x# bindkey "^[L" down-case-word
#x# bindkey "^[N" history-search-forward
bindkey "^[OA" up-line-or-history
bindkey "^[OB" down-line-or-history
#x# bindkey "^[OC" forward-char
#x# bindkey "^[OD" backward-char
#x# bindkey "^[P" history-search-backward
#x# bindkey "^[Q" push-line
#x# bindkey "^[S" spell-word
#xx# bindkey "^[T" transpose-words
#xx# bindkey "^[U" up-case-word
#?# bindkey "^[W" copy-region-as-kill
bindkey "^[[A" up-line-or-history
bindkey "^[[B" down-line-or-history
bindkey "^[[C" forward-char
bindkey "^[[D" backward-char
bindkey "^[_" insert-last-word
#?# bindkey "^[a" accept-and-hold
#?# bindkey "^[b" backward-word
#?# bindkey "^[c" capitalize-word
#?# bindkey "^[d" kill-word
#?# bindkey "^[f" forward-word
#?# bindkey "^[g" get-line
#?# bindkey "^[h" run-help
#?# bindkey "^[l" down-case-word
#?# bindkey "^[n" history-search-forward
#?# bindkey "^[p" history-search-backward
#?# bindkey "^[q" push-line
#?# bindkey "^[s" spell-word
#?# bindkey "^[t" transpose-words
#?# bindkey "^[u" up-case-word
#?# bindkey "^[w" copy-region-as-kill
#?# bindkey "^[x" execute-named-cmd
#?# bindkey "^[y" yank-pop
#?# bindkey "^[z" execute-last-named-cmd
#?# bindkey "^[|" vi-goto-column
#?# bindkey "^[^?" backward-kill-word
#?# bindkey "^_" undo
#?# bindkey "^?" backward-delete-char
